### PR TITLE
Offered suggestions to Jeff for the TAS DSS submission

### PR DESCRIPTION
**Pull request by nicholasjhorton**
As part of the review that Jenny Bryan requested, I've made some minor wording suggestions and changes to what is otherwise an excellent and very useful piece. Feel free to incorporate or ignore as you see fit.

Two additional suggestions (perhaps only for the DSS submission):
(1) Add an example with fake data for the genomics example (under "the tidy data set")
(2) Add some references for more background on the topic (and a broader connection to the scientific irreproducibility world) 
         - Hadley Tidy data
         - http://www.pnas.org/content/112/6/1645
         - http://www.nature.com/news/reproducibility-1.17552

### CODE REVIEW

**Comment by ProgramSupport** [comment]
The explanation is very precise and excellant

**Comment by AluruRavindraBabu** [comment]
As part of the review the assignment for Hector Morales.

One suggestion provided

Please fork to https://github.com/jtleek/datasharin

**Comment by danieldelgado08** [comment]
muy buena explicación sobre los datos, de manera contundente pauta los pasos a seguir.

**Comment by DajmanNatz** [comment]
clearly explained

**Comment by harshalkshirsagar** [comment]
https://github.com/harshalkshirsagar/datasciencecoursera/blob/master/HelloWorld.md

please fork my doc. for the purpose of coursera project

**Comment by mahelaly** [comment]
https://github.com/mahelaly/datasciencecoursera/blob/master/HelloWorld.Rmd

please fork my doc. for the purpose of coursera project

**Comment by mahelaly** [comment]
https://github.com/mahelaly/datasciencecoursera/blob/master/HelloWorld.md

please fork my doc. for the purpose of coursera project

**Comment by krizagbon** [comment]
https://github.com/krizagbon/datasciencecoursera.git
Hello, please fork my doc. for coursera!
Thanks

**Comment by iamvijaym** [comment]
Please Fork my Repository
https://github.com/iamvijaym/datasciencecoursera.git

**Comment by dasshubham143** [comment]
Fork my repo :-

https://github.com/dasshubham143/datasciencecoursera.git

**Comment by NavenHon** [comment]
https://github.com/jtleek/datasharing

**Comment by danielaqvivas** [comment]
https://github.com/danielaqvivas/Datasciencecoursera.git

**Comment by guanyingkai1984** [comment]
Fork my repo :-

https://github.com/jtleek/datasharing/issues/1043
https://github.com/guanyingkai1984/datasharing
https://github.com/guanyingkai1984/datasciencecoursera.git

**Comment by lolo023** [comment]
https://github.com/lolo023/datasharing.git

**Comment by AlejoDataTech** [comment]
Hola! 
Muy buena información; Podria porfavor bifurcar mi repositorio, es para mi proyecto de coursera
https://github.com/AlejoDataTech/datasciencecoursera

**Comment by AHakimsoil** [comment]
Please Fork my Repository

https://github.com/AHakimsoil/datasharing
 for the purpose of coursera project

**Pull request merged**
